export type CompileOptions = {
  wildcardMode?: boolean;
};

export type CompileIssue = {
  line: number;
  message: string;
  source: string;
};

export type CompileResult = {
  js: string;
  issues: CompileIssue[];
};

type BlockType = "if" | "while" | "for" | "repeat";

type BlockEntry = {
  type: BlockType;
  line: number;
};

const INDENT = "  ";

function stripDiacritics(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

function normalizeForMatch(line: string) {
  return stripDiacritics(line)
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeOperators(expression: string) {
  let out = expression.trim();

  out = out
    .replace(/\u2260/g, "!=")
    .replace(/\u2264/g, "<=")
    .replace(/\u2265/g, ">=")
    .replace(/\bdiv\b/gi, "/")
    .replace(/\bmod\b/gi, "%")
    .replace(/\bsi\b/gi, "&&")
    .replace(/\bsau\b/gi, "||")
    .replace(/\bnu\b/gi, "!");

  // Convert [x] from pseudocode to integer floor semantics.
  out = out.replace(/\[([^\[\]]+)\]/g, "Math.floor($1)");

  // Convert standalone = to strict equality while preserving <=, >=, != and ==.
  out = out.replace(/([^<>!=])=([^=])/g, "$1===$2");
  out = out.replace(/^=([^=])/g, "===$1");

  return out;
}

function parseForLine(line: string) {
  const normalized = normalizeForMatch(line);
  const match = normalized.match(
    /^pentru\s+([a-z_][a-z0-9_]*)\s*(?:<-|=)\s*(.+?)\s*,\s*(.+?)(?:\s+pas\s+(.+?))?(?:\s+executa)?$/i,
  );

  if (!match) {
    return null;
  }

  const variable = match[1];
  const start = normalizeOperators(match[2]);
  const end = normalizeOperators(match[3]);
  const step = normalizeOperators(match[4] ?? "1");

  return { variable, start, end, step };
}

function parseReadVariables(line: string) {
  const readMatch = line.match(/^\s*(?:citeste|cite?ste|read)\s+(.+)$/i);
  if (!readMatch) {
    return null;
  }

  return readMatch[1]
    .split(",")
    .map((token) => token.trim())
    .filter(Boolean)
    .filter((token) => /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(token));
}

function parseWriteArgs(line: string) {
  const writeMatch = line.match(/^\s*(?:scrie|afiseaza|afi?seaza|print|write)\s+(.+)$/i);
  if (!writeMatch) {
    return null;
  }

  return writeMatch[1]
    .split(",")
    .map((token) => normalizeOperators(token))
    .filter(Boolean);
}

function parseAssignment(line: string) {
  const assignMatch = line.match(/^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?:<-|\u2190)\s*(.+)$/);
  if (!assignMatch) {
    return null;
  }

  return {
    variable: assignMatch[1],
    expression: normalizeOperators(assignMatch[2]),
  };
}

function currentIndent(level: number) {
  return INDENT.repeat(Math.max(level, 0));
}

export function compilePseudocode(input: string, options: CompileOptions = {}): CompileResult {
  const wildcardMode = options.wildcardMode ?? true;
  const lines = input.replace(/\r\n/g, "\n").split("\n");

  const generated: string[] = [];
  const issues: CompileIssue[] = [];
  const declaredVars = new Set<string>();
  const stack: BlockEntry[] = [];

  let indentLevel = 0;

  generated.push("// Generated by pseudocode compiler");
  generated.push("const __outputs = [];");
  generated.push(
    "function __read(label) { const raw = typeof prompt === 'function' ? prompt(label) : '0'; const value = Number(raw); return Number.isNaN(value) ? raw ?? '' : value; }",
  );
  generated.push("function __write(...values) { __outputs.push(values.join(' ')); console.log(...values); }");
  generated.push("");

  for (let i = 0; i < lines.length; i += 1) {
    const source = lines[i];
    const trimmed = source.trim();

    if (!trimmed) {
      generated.push("");
      continue;
    }

    const normalized = normalizeForMatch(trimmed);

    if (normalized.startsWith("//") || normalized.startsWith("#")) {
      generated.push(`${currentIndent(indentLevel)}// ${trimmed.replace(/^\s*(?:#|\/\/)+\s*/, "")}`);
      continue;
    }

    if (/^altfel$/.test(normalized)) {
      const top = stack[stack.length - 1];
      if (!top || top.type !== "if") {
        issues.push({ line: i + 1, message: "`altfel` fara `daca` corespunzator.", source });
        continue;
      }

      indentLevel -= 1;
      generated.push(`${currentIndent(indentLevel)}} else {`);
      indentLevel += 1;
      continue;
    }

    if (/^(sfarsit_daca|sfarsit daca|endif|end if)$/.test(normalized)) {
      const top = stack.pop();
      if (!top || top.type !== "if") {
        issues.push({ line: i + 1, message: "`sfarsit_daca` fara bloc `daca` deschis.", source });
        continue;
      }

      indentLevel -= 1;
      generated.push(`${currentIndent(indentLevel)}}`);
      continue;
    }

    if (/^(sfarsit_cat_timp|sfarsit cat timp|sfarsit_while|end while)$/.test(normalized)) {
      const top = stack.pop();
      if (!top || top.type !== "while") {
        issues.push({ line: i + 1, message: "`sfarsit_cat_timp` fara bloc `cat timp` deschis.", source });
        continue;
      }

      indentLevel -= 1;
      generated.push(`${currentIndent(indentLevel)}}`);
      continue;
    }

    if (/^(sfarsit_pentru|sfarsit pentru|end for)$/.test(normalized)) {
      const top = stack.pop();
      if (!top || top.type !== "for") {
        issues.push({ line: i + 1, message: "`sfarsit_pentru` fara bloc `pentru` deschis.", source });
        continue;
      }

      indentLevel -= 1;
      generated.push(`${currentIndent(indentLevel)}}`);
      continue;
    }

    const untilMatch = normalized.match(/^(pana\s+cand|until)\s+(.+)$/i);
    if (untilMatch) {
      const top = stack.pop();
      if (!top || top.type !== "repeat") {
        issues.push({ line: i + 1, message: "`pana cand` fara bloc `repeta` deschis.", source });
        continue;
      }

      indentLevel -= 1;
      const condition = normalizeOperators(untilMatch[2]);
      generated.push(`${currentIndent(indentLevel)}} while (!(${condition}));`);
      continue;
    }

    const ifMatch = normalized.match(/^(daca|if)\s+(.+?)\s+atunci$/i);
    if (ifMatch) {
      const condition = normalizeOperators(ifMatch[2]);
      generated.push(`${currentIndent(indentLevel)}if (${condition}) {`);
      stack.push({ type: "if", line: i + 1 });
      indentLevel += 1;
      continue;
    }

    const whileMatch = normalized.match(/^(cat\s+timp|while)\s+(.+?)\s*(executa|do)?$/i);
    if (whileMatch) {
      const condition = normalizeOperators(whileMatch[2]);
      generated.push(`${currentIndent(indentLevel)}while (${condition}) {`);
      stack.push({ type: "while", line: i + 1 });
      indentLevel += 1;
      continue;
    }

    if (/^(repeta|repeat)$/.test(normalized)) {
      generated.push(`${currentIndent(indentLevel)}do {`);
      stack.push({ type: "repeat", line: i + 1 });
      indentLevel += 1;
      continue;
    }

    const parsedFor = parseForLine(trimmed);
    if (parsedFor) {
      const { variable, start, end, step } = parsedFor;
      const stepName = `__step_${variable}_${i + 1}`;
      generated.push(`${currentIndent(indentLevel)}const ${stepName} = (${step});`);
      generated.push(
        `${currentIndent(indentLevel)}for (let ${variable} = (${start}); ${stepName} >= 0 ? ${variable} <= (${end}) : ${variable} >= (${end}); ${variable} += ${stepName}) {`,
      );
      declaredVars.add(variable);
      stack.push({ type: "for", line: i + 1 });
      indentLevel += 1;
      continue;
    }

    const readVariables = parseReadVariables(trimmed);
    if (readVariables) {
      if (readVariables.length === 0) {
        issues.push({ line: i + 1, message: "`citeste` nu are variabile valide.", source });
        continue;
      }

      for (const variable of readVariables) {
        const statement = declaredVars.has(variable)
          ? `${variable} = __read("${variable} = ");`
          : `let ${variable} = __read("${variable} = ");`;
        generated.push(`${currentIndent(indentLevel)}${statement}`);
        declaredVars.add(variable);
      }
      continue;
    }

    const writeArgs = parseWriteArgs(trimmed);
    if (writeArgs) {
      if (writeArgs.length === 0) {
        issues.push({ line: i + 1, message: "`scrie` nu are expresii valide.", source });
        continue;
      }

      generated.push(`${currentIndent(indentLevel)}__write(${writeArgs.join(", ")});`);
      continue;
    }

    const assignment = parseAssignment(trimmed);
    if (assignment) {
      const { variable, expression } = assignment;
      const statement = declaredVars.has(variable)
        ? `${variable} = ${expression};`
        : `let ${variable} = ${expression};`;
      generated.push(`${currentIndent(indentLevel)}${statement}`);
      declaredVars.add(variable);
      continue;
    }

    if (wildcardMode) {
      // In wildcard mode, unknown lines are preserved as comments to avoid losing intent.
      generated.push(`${currentIndent(indentLevel)}// [wildcard] ${trimmed}`);
      issues.push({
        line: i + 1,
        message: "Linie necunoscuta; pastrata ca comentariu in modul wildcard.",
        source,
      });
      continue;
    }

    issues.push({ line: i + 1, message: "Instructiune necunoscuta.", source });
  }

  while (stack.length > 0) {
    const open = stack.pop();
    if (!open) {
      break;
    }

    indentLevel -= 1;
    if (open.type === "repeat") {
      generated.push(`${currentIndent(indentLevel)}} while (true);`);
      issues.push({
        line: open.line,
        message: "Bloc `repeta` neinchis; s-a adaugat inchidere implicita.",
        source: lines[open.line - 1] ?? "",
      });
      continue;
    }

    generated.push(`${currentIndent(indentLevel)}}`);
    issues.push({
      line: open.line,
      message: `Bloc \`${open.type}\` neinchis; s-a adaugat inchidere implicita.`,
      source: lines[open.line - 1] ?? "",
    });
  }

  generated.push("");
  generated.push("// Output captured during execution");
  generated.push("__outputs;");

  return {
    js: generated.join("\n"),
    issues,
  };
}
